# Generated by Django 4.1.7 on 2023-03-09 11:12

import autoslug.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='09/03/2023 16:57:06', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=home.models.UserProfile.fileName),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seller_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
