# Generated by Django 4.1.7 on 2023-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userprofile_date_of_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='09/03/2023 17:01:06', max_length=40),
        ),
    ]
