# Generated by Django 4.1.5 on 2023-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_date_of_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_verified_on',
            field=models.CharField(default='Not Verified', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='09/03/2023 22:03:30', max_length=40),
        ),
    ]
