# Generated by Django 4.1.5 on 2023-03-10 07:59

import autoslug.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile_account_verified_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_photo',
            field=models.ImageField(blank=True, upload_to=home.models.Book.fileName),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='book_name', unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_added',
            field=models.CharField(default='10/03/2023 13:44:37', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='10/03/2023 13:44:37', max_length=40),
        ),
    ]
