# Generated by Django 4.1.5 on 2023-03-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_book_book_cover_photo_alter_book_book_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_added',
            field=models.CharField(default='10/03/2023 13:46:46', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='10/03/2023 13:46:46', max_length=40),
        ),
    ]
