# Generated by Django 4.1.5 on 2023-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_date_of_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_added',
            field=models.CharField(default='10/03/2023 13:54:25', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='10/03/2023 13:54:25', max_length=40),
        ),
    ]
