# Generated by Django 4.1.5 on 2023-03-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_date_of_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_added',
            field=models.CharField(default='10/03/2023 17:16:18', max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='10/03/2023 17:16:18', max_length=40),
        ),
    ]
