# Generated by Django 4.1.5 on 2023-03-10 12:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_book_date_of_added_alter_book_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='book_category', unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_added',
            field=models.CharField(default='10/03/2023 18:25:23', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='10/03/2023 18:25:23', max_length=40),
        ),
    ]
