# Generated by Django 4.1.7 on 2023-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book_book_category_slug_alter_book_date_of_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_added',
            field=models.CharField(default='11/03/2023 01:22:20', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_register',
            field=models.CharField(default='11/03/2023 01:22:20', max_length=40),
        ),
    ]
